In [0]:
import pandas as pd
print("pandas version: %s" % pd.__version__)
import matplotlib
print("matplotlib version: %s" % matplotlib.__version__)
import numpy as np
print("numpy version: %s" % np.__version__)
import sklearn
print("scikit-learn version: %s" % sklearn.__version__)

pandas version: 0.25.3
matplotlib version: 3.1.1
numpy version: 1.17.4
scikit-learn version: 0.21.3


In [0]:
arr = np.array([1.887, 4, 2, 8, 5, 7], dtype='float')
print("%s\nndim: %s, shape: %s, dtype: %s" % (arr, arr.ndim, arr.shape, arr.dtype))

f_arr = arr.astype(int)
print(f_arr)

[1.887 4.    2.    8.    5.    7.   ]
ndim: 1, shape: (6,), dtype: float64
[1 4 2 8 5 7]


How to build an array?

In [0]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
print(x)

x = np.zeros((2, 3))
print(x)

x = np.ones((2, 3))
print(x)

x = np.eye(3)
print(x)

x = np.arange(2, 3, 0.1)
print(x)

x = np.linspace(2, 3, 6)
print(x)

x = np.indices((2, 3))
print(x)

[[1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
[2.  2.2 2.4 2.6 2.8 3. ]
[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]


In [0]:
arr = np.arange(24)
print(arr)

arr = arr.reshape(2, 3, 4)
print(arr)

print(arr.ravel())

print(arr.T)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [0]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); 
print(ar)
print(ar[1,2])
print(ar[2,:])
print(ar[:,1])
print(ar[2,-1])

[[ 2  3  4]
 [ 9  8  7]
 [11 12 13]]
7
[11 12 13]
[ 3  8 12]
13


In [0]:
ar = range(1000)
%timeit [ar[i]**3 for i in ar]

1000 loops, best of 3: 363 µs per loop


In [0]:
ar = np.arange(1000)
%timeit ar**3

The slowest run took 22.95 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.49 µs per loop
